### ISSUE TITLE
Lamp: characteristic SET handler returned write response value error

### ISSUE THREAD

**Issue by jarz** [hjdhjd/homebridge-myq#1107]
**Describe The Problem:**
Homebridge logs the following error when toggling a lamp accessory on or off via the Home.app: `Characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://homebridge.io/w/JtMGR for more info.`

**To Reproduce:**
Turn a lamp accessory on or off via Home.app.

**Logs:**
```
[9/9/2023, 4:41:07 PM] [homebridge-myq] Characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://homebridge.io/w/JtMGR for more info.
logger.js:121
[9/9/2023, 4:41:07 PM] [homebridge-myq] Error: 
    at On.Characteristic.characteristicWarning (/Users/tim/code/github/jarz/homebridge-myq/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at On.<anonymous> (/Users/tim/code/github/jarz/homebridge-myq/node_modules/hap-nodejs/src/lib/Characteristic.ts:2557:18)
    at step (/Users/tim/code/github/jarz/homebridge-myq/node_modules/hap-nodejs/node_modules/tslib/tslib.js:193:27)
    at Object.next (/Users/tim/code/github/jarz/homebridge-myq/node_modules/hap-nodejs/node_modules/tslib/tslib.js:174:57)
    at fulfilled (/Users/tim/code/github/jarz/homebridge-myq/node_modules/hap-nodejs/node_modules/tslib/tslib.js:164:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Homebridge Configuration:**

_N/A_

**Screenshots:**

_N/A_

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** v18.16.0
* **Homebridge-myQ Plugin Version**: 3.4.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Apple TV 4K (1st Generation) tvOS 16.5
* **Operating System and OS Version:** Docker `homebridge/homebridge@latest`

**Comment by hjdhjd** [comment]
How many reports are you going to open for the same thing? 😄

**Comment by jarz** [comment]
For a while I thought this was the same as #1107, until I fixed that one and kept seeing this appear.

I've got to be one of like three people using these, but it's been useful for some experiments.
