### ISSUE TITLE
myQ API Unable to Authenticate

### ISSUE THREAD

**Issue by andrewturko** [hjdhjd/homebridge-myq#114]
Receiving another error related to authentication.

____

[9/16/2020, 7:13:42 PM] [Garage] FetchError: request to https://api.myqdevice.com/api/v5/Login failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-myq2/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:314:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}
[9/16/2020, 7:13:42 PM] [Garage] myQ API: Unable to authenticate. Will retry later.

**Comment by hjdhjd** [comment]
Please use the issue template to report problems. What you've posted is insufficient to help you. You also appear to be on an old version of the plugin - uninstall it and install homebridge-myq instead.

Thanks!
