### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by 6uv1s** [hjdhjd/homebridge-myq#212]
**Describe The Problem:**

the myq plugin does not load with syntax error.
**To Reproduce:**

Install/load latest plugin.
**Logs:**

```
[2020-12-27 00:42:56] ERROR LOADING PLUGIN homebridge-myq:
[2020-12-27 00:42:56] /home/pi/node_modules/node-fetch/dist/index.cjs:177
async function * formDataIterator(form, boundary) {
^

SyntaxError: Unexpected token *
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:617:28)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object. (/home/pi/node_modules/homebridge-myq/src/myq-api.ts:13:1)
```

**Homebridge Configuration:**

```json
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 2.4.0
* **Node Version:** 8.15.0
* **Homebridge-myQ Plugin Version**:
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Apple TV
* **Operating System and OS Version:** Raspbian

**Comment by jarz** [comment]
@6uv1s That's a really old version of node that isn't supported by Homebridge anymore.

> Homebridge (and verified plugins) support all current Active and Maintenance LTS releases of Node.js. At the time of writing, this means we will support:
>    Node.js 10.x until April 2021
    Node.js 12.x until April 2022
    Node.js 14.x until April 2023
    Node.js 16.x from October 2021 until April 2024
> Homebridge does not support odd-numbered releases of Node.js, such as 11.x, 13.x or 15.x.

[ref](https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js)

I'm not seeing this error on node 12.18.3.

**Comment by hjdhjd** [comment]
You’re running an ancient version of Node @6uv1s. 😄 

Slight aside...@jarz You’re running an ancient version yourself. The Active LTS supported version of node will be node 14. I’ll be deprecating support for node 12 in January, for my plugins: https://nodejs.org/en/about/releases/
