### ISSUE TITLE
/home/hoobs/.hoobs/node_modules/homebridge-myq2 plugin created after updating

### ISSUE THREAD

**Issue by effxiikc** [hjdhjd/homebridge-myq#243]
**Describe The Problem:**

When I update homebridge-myq or any other plugin, I keep getting a new plugin created by myQ with the following path

/home/hoobs/.hoobs/node_modules/homebridge-myq2

My hoobs will then fail to start the service and I have to manually go into terminal to delete this file path in order for the service to start successfully again.

Any one have the same issue or know what's wrong?

**To Reproduce:**

Update hoobs or update homebridge-myq

**Logs:**

```
1/19/2021, 10:29:42 PM HOOBS listening on port 80.
1/19/2021, 10:29:45 PM Loaded plugin 'homebridge-camera-ffmpeg'
1/19/2021, 10:29:45 PM [1/19/2021, 10:29:45 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
1/19/2021, 10:29:45 PM Loaded plugin 'homebridge-myq'
1/19/2021, 10:29:45 PM [1/19/2021, 10:29:45 PM] Registering platform 'homebridge-myq.myQ'
1/19/2021, 10:29:45 PM Loaded plugin 'homebridge-myq2'
1/19/2021, 10:29:45 PM [1/19/2021, 10:29:45 PM] Registering platform 'homebridge-myq2.myQ'
1/19/2021, 10:29:45 PM Loaded plugin 'homebridge-nest-cam'
1/19/2021, 10:29:45 PM [1/19/2021, 10:29:45 PM] Registering platform 'homebridge-nest-cam.Nest-cam'
1/19/2021, 10:29:45 PM Loaded plugin 'homebridge-tplink-smarthome'
1/19/2021, 10:29:45 PM Loading 4 platforms...
1/19/2021, 10:29:45 PM [1/19/2021, 10:29:45 PM] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
1/19/2021, 10:29:45 PM [TplinkSmarthome] Initializing TplinkSmarthome platform...
1/19/2021, 10:29:45 PM [TplinkSmarthome] homebridge-tplink-smarthome v6.1.0, node v12.16.3, homebridge v1.1.7
1/19/2021, 10:29:45 PM [Nest-cam] Initializing Nest-cam platform...
1/19/2021, 10:29:45 PM [Camera FFmpeg] Initializing Camera-ffmpeg platform...
1/19/2021, 10:29:45 PM Error loading platform requested in your config.json at position 4
1/19/2021, 10:29:45 PM Error: The requested platform 'myQ' has been registered multiple times. Please be more specific by writing one of: homebridge-myq.myQ, homebridge-myq2.myQ
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:156:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:334:45
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:**  1.1.2
* **Node Version:**  12.16.3
* **Homebridge-myQ Plugin Version**: 2.4.2
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS
* **Operating System and OS Version:**  Windows 10

**Comment by jarz** [comment]
`homebridge-myq2` is the former name of this plugin. I just checked the source code and don't see any references to the old name.

I don't use HOOBS, but maybe this will help: https://github.com/hoobs-org/HOOBS/issues/812

**Comment by jarz** [comment]
See also https://github.com/hjdhjd/homebridge-myq/issues/117#issuecomment-703715431

**Comment by hjdhjd** [comment]
@jarz is correct. Best of luck.
