### ISSUE TITLE
Homebridge encounters error loading plugin

### ISSUE THREAD

**Issue by hollandcloud** [hjdhjd/homebridge-myq#434]
Latest plugin version isn't loading - I'm getting an error on loading an ES Module:

Homebridge Version: 1.3.4
NodeJS Version: 12.22.1
NPM Version: 6.14.12
homebridge-myq version: 2.6.2

[7/19/2021, 08:30:29] ====================
[7/19/2021, 08:30:29] ERROR LOADING PLUGIN homebridge-myq:
[7/19/2021, 08:30:29] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/lib/node_modules/homebridge-myq/node_modules/node-fetch/src/index.js
require() of ES modules is not supported.
require() of /usr/lib/node_modules/homebridge-myq/node_modules/node-fetch/src/index.js from /usr/lib/node_modules/homebridge-myq/dist/myq-api.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/lib/node_modules/homebridge-myq/node_modules/node-fetch/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-myq/src/myq-api.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
[7/19/2021, 08:30:29] ====================

**Comment by hjdhjd** [comment]
Update coming shortly!

**Comment by hjdhjd** [comment]
Try the latest version. Good luck.
