### ISSUE TITLE
"RangeError: Maximum call stack size exceeded" does not allow homebridge to run

### ISSUE THREAD

**Issue by saborski** [hjdhjd/homebridge-myq#590]
**Describe The Problem:**
"RangeError: Maximum call stack size exceeded" does not allow homebridge to run

**To Reproduce:**
install homebridge-myq from homebridge gui

**Logs:**

```
[12/24/2021, 1:19:06 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[12/24/2021, 1:19:06 PM] [HB Supervisor] Started Homebridge v1.3.8 with PID: 6195
[12/24/2021, 1:19:07 PM] Loaded config.json with 0 accessories and 3 platforms.
[12/24/2021, 1:19:07 PM] Loaded 14 cached accessories from cachedAccessories.
[12/24/2021, 1:19:07 PM] ---
[12/24/2021, 1:19:07 PM] Loaded plugin: homebridge-config-ui-x@4.41.5
[12/24/2021, 1:19:07 PM] Registering platform 'homebridge-config-ui-x.config'
[12/24/2021, 1:19:07 PM] ---
[12/24/2021, 1:19:07 PM] Loaded plugin: homebridge-myq@2.7.1
[12/24/2021, 1:19:07 PM] Registering platform 'homebridge-myq.myQ'
[12/24/2021, 1:19:07 PM] ---
[12/24/2021, 1:19:07 PM] Loaded plugin: homebridge-unifi-protect@4.4.3
[12/24/2021, 1:19:07 PM] Registering platform 'homebridge-unifi-protect.UniFi Protect'
[12/24/2021, 1:19:07 PM] ---
[12/24/2021, 1:19:07 PM] Loading 3 platforms...
[12/24/2021, 1:19:07 PM] [Config] Initializing config platform...
[12/24/2021, 1:19:07 PM] [Config] Running in Service Mode
[12/24/2021, 1:19:07 PM] [UniFi Protect] Initializing UniFi Protect platform...
[12/24/2021, 1:19:07 PM] [myq-g-garage] Initializing myQ platform...
[12/24/2021, 1:19:07 PM] [myq-g-garage] Debug logging on. Expect a lot of data.
[12/24/2021, 1:19:07 PM] RangeError: Maximum call stack size exceeded
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
[12/24/2021, 1:19:07 PM] Got SIGTERM, shutting down Homebridge...
[12/24/2021, 1:19:10 PM] [myq-g-garage] myQ API: Successfully connected to the myQ API.
[12/24/2021, 1:19:11 PM] [myq-g-garage] {
accounts: [
{
created_by: 'fd73ecd5-2211-4024-ba93-b122dd948d5c',
id: '65e8e35c-789d-442e-b4c7-e567d343785d',
max_users: { co_owner: 2, guest: 5 },
name: "G's Home"
}
]
}
[12/24/2021, 1:19:12 PM] [myq-g-garage] {
accounts: [
{
created_by: 'fd73ecd5-2211-4024-ba93-b122dd948d5c',
id: '65e8e35c-789d-442e-b4c7-e567d343785d',
max_users: { co_owner: 2, guest: 5 },
name: "G's Home"
}
]
}
[12/24/2021, 1:19:13 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[12/24/2021, 1:19:18 PM] [HB Supervisor] Restarting Homebridge...
[12/24/2021, 1:19:18 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[12/24/2021, 1:19:18 PM] [HB Supervisor] Started Homebridge v1.3.8 with PID: 6244
[12/24/2021, 1:19:18 PM] Loaded config.json with 0 accessories and 3 platforms.
[12/24/2021, 1:19:18 PM] Loaded 14 cached accessories from cachedAccessories.
[12/24/2021, 1:19:18 PM] ---
[12/24/2021, 1:19:18 PM] Loaded plugin: homebridge-config-ui-x@4.41.5
[12/24/2021, 1:19:18 PM] Registering platform 'homebridge-config-ui-x.config'
[12/24/2021, 1:19:18 PM] ---
[12/24/2021, 1:19:18 PM] Loaded plugin: homebridge-myq@2.7.1
[12/24/2021, 1:19:18 PM] Registering platform 'homebridge-myq.myQ'
[12/24/2021, 1:19:18 PM] ---
[12/24/2021, 1:19:19 PM] Loading 3 platforms...
[12/24/2021, 1:19:19 PM] [Config] Initializing config platform...
[12/24/2021, 1:19:19 PM] [Config] Running in Service Mode
[12/24/2021, 1:19:19 PM] [UniFi Protect] Initializing UniFi Protect platform...
[12/24/2021, 1:19:19 PM] [myq-g-garage] Initializing myQ platform...
[12/24/2021, 1:19:19 PM] [myq-g-garage] Debug logging on. Expect a lot of data.
[12/24/2021, 1:19:19 PM] RangeError: Maximum call stack size exceeded
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-myq/node_modules/collections/shim-array.js:31:22)
[12/24/2021, 1:19:19 PM] Got SIGTERM, shutting down Homebridge...
```

**Homebridge Configuration:**

```json
{
    "bridge": {
        "name": "Homebridge 7274",
        "username": "",
        "port": 51994,
        "pin": "",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 80,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "controllers": [
                {
                    "address": "cloudkey",
                    "password": "",
                    "username": ""
                }
            ],
            "platform": "UniFi Protect"
        },
        {
            "email": "",
            "password": "",
            "name": "myq-g-garage",
            "debug": true,
            "platform": "myQ"
        }
    ]
}

```

**Environment:**

* **Homebridge Version: 1.3.8** 
* **Node Version:v16.13.1** 
* **Homebridge-myQ Plugin Version homebridge-myq v2.7.1**:
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:iphone 13 pro max ios 15.2**
* **Operating System and OS Version:ubuntu 20.04 lxd container** *

**Comment by aaronkbutler** [comment]
Same issue here
