### ISSUE TITLE
Multiple MyQ Hubs

### ISSUE THREAD

**Issue by Dirtrunner702** [hjdhjd/homebridge-myq#723]
**Is your feature request related to a problem? Please describe:**

Cannot seem to add multiple MyQ hubs with separate login information from one another. 

**Describe the solution you'd like:**
Ability to add more than one MyQ hubs to the plugin

**Describe alternatives you've considered:**
I have tried running another MyQ/Chamberlain plugin but they have not been updated in a long time so they do not work at all. 

**Additional context:**
Thank you for all the contribution to the plugin!

**Comment by hjdhjd** [comment]
Appreciate the request, but to clarify: all myQ hubs associated with an account already are exposed by this plugin. If you have multiple accounts, just add a second instance of the plugin with those credentials.

If your use case isn't one of the above...please elaborate. 😄

**Comment by Dirtrunner702** [comment]
Thanks for the reply! So I try to add a second instance and then get the following. 
If i can provide another log of some sort just let me know how to pull it. Im running the Homebridge linux appliance as a VM. 

This is my config file 
{
            "email": "email1@gmail.com",
            "password": "PW",
            "name": "Our Garage Door",
            "platform": "myQ"
        },
        {
            "email": "Email2@gmail.com",
            "password": "Otherpw",
            "name": "Parents Garage Door",
            "platform": "myQ"
        }

[5/16/2022, 11:46:24 AM] [Our Garage Door] Initializing myQ platform...
[5/16/2022, 11:46:24 AM] The dynamic platform myQ from the plugin homebridge-myq seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!
[5/16/2022, 11:46:24 AM] [Parents Garage Door] Initializing myQ platform...
[5/16/2022, 11:46:24 AM] [homebridge-myq] Could not restore cached accessory 'My Garage': Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 8b153fa7-388f-4924-be0f-7d4ee61dd76a

[5/16/2022, 11:43:19 AM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 8b153fa7-388f-4924-be0f-7d4ee61dd76a
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:594:15)
    at Bridge.Accessory.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:623:12)
    at BridgeService.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:384:17)
    at HomebridgeAPI.emit (node:events:527:28)
    at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:340:10)
    at myQPlatform.discoverAndSyncAccessories (/homebridge/node_modules/homebridge-myq/src/myq-platform.ts:223:18)
    at myQPlatform.updateAccessories (/homebridge/node_modules/homebridge-myq/src/myq-platform.ts:290:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /homebridge/node_modules/homebridge-myq/src/myq-platform.ts:326:14
[5/16/2022, 11:43:19 AM] Got SIGTERM, shutting down Homebridge...

**Comment by hjdhjd** [comment]
Use a child bridge. It's covered in the Homebridge documentation. :smile:

**Comment by Dirtrunner702** [comment]
Ive gone through all the documentation that I could find and did not see that portion. Do you have a link you can share with me to it?

**Comment by hjdhjd** [comment]
https://github.com/homebridge/homebridge/wiki/Child-Bridges

**Comment by Dirtrunner702** [comment]
Thank you for your time! Sorry to bug ya!

**Comment by hjdhjd** [comment]
No worries!
